#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(PORTEFOLIOMANAGERUTILITIES_LIB)
#  define PORTEFOLIOMANAGERUTILITIES_EXPORT Q_DECL_EXPORT
# else
#  define PORTEFOLIOMANAGERUTILITIES_EXPORT Q_DECL_IMPORT
# endif
#else
# define PORTEFOLIOMANAGERUTILITIES_EXPORT
#endif
